AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for creating VPC Transit Gateway Attachment'

Parameters:

  VSFATTACH:
    Description: San Francisco VPN Attachment
    Type: String
    Default: tgw-attach-08f9ea1b799ea2732

  VPDXATTACH:
    Description: Portland VPN Attachment
    Type: String
    Default: tgw-attach-0b3f92f7bb9f6c86e

  VSTLATTACH:
    Description: St Louis VPN Attachment
    Type: String
    Default: tgw-attach-0caeb220bbbc103e6

  VBZATTACH:
    Description: Bellenzona VPN Attachment
    Type: String
    Default: tgw-attach-04fba10c06188714f

#UPDATE CHILD VPC NAME

  VPCNAME:
    Description: VPC Name
    Type: String
    Default: BIO-INFORMATICS-PROD

#UPDATE CHILD VPC ID

  VPCID:
    Description: VPC ID
    Type: String
    Default: vpc-009d7a872f6d2e92a

  LOCATION:
    Description: AWS Region
    Type: String
    AllowedValues:
      - USW2
      - USE1
      - EUC1


#  INFRASTRUCTURERTB:
#      Description: Infrastructure VPC Route Table
#      Type: String
#      Default: tgw-rtb-0899b05f8732a71e2


  ONPREMRTB:
    Description: Default Route Table
    Type: String
    Default: tgw-rtb-06fb1a0a41edb79a2

  PVTSUBNET1:
    Description: Public Subnet ID in AZ1
    Type: String
    Default: subnet-08bce6b3eed918ac5

  PVTSUBNET2:
    Description: Public Subnet ID in AZ2
    Type: String
    Default: subnet-0e10b9c810240cad8

  TGWID:
    Description:  Transit Gateway ID (USW2-TGW-0636048e0a4a4d640 / USE1-TGW-0f420529ad2f44f8b)
    Type: String
    AllowedValues:
      - tgw-0636048e0a4a4d640
      - tgw-0f420529ad2f44f8b

Resources:
  VIRBIOINFOPRODATTACH:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId: !Ref "TGWID"
      VpcId: !Ref "VPCID"
      SubnetIds:
        - !Ref "PVTSUBNET1"
        - !Ref "PVTSUBNET2"

      Tags:
        - Key: Name
          Value: !Ref "VPCNAME"

  VIRBIOINFOPRODRTB:
    Type: "AWS::EC2::TransitGatewayRouteTable"
    Properties:
      TransitGatewayId: !Ref "TGWID"
      Tags:
        - Key: Name
          Value: !Ref "VPCNAME"

  VIRBIOINFOPRODRTBASSOCIATION:
    Type: "AWS::EC2::TransitGatewayRouteTableAssociation"
    DependsOn: VIRBIOINFOPRODRTB
    Properties:
      TransitGatewayAttachmentId: !Ref "VIRBIOINFOPRODATTACH"
      TransitGatewayRouteTableId: !Ref "VIRBIOINFOPRODRTB"

  VIRBIOINFOPRODRTBPROPAGATIONVSF:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VSFATTACH"
      TransitGatewayRouteTableId: !Ref "VIRBIOINFOPRODRTB"

  VIRBIOINFOPRODRTBPROPAGATIONPDX:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VPDXATTACH"
      TransitGatewayRouteTableId: !Ref "VIRBIOINFOPRODRTB"

  VIRBIOINFOPRODRTBPROPAGATIONSTL:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VSTLATTACH"
      TransitGatewayRouteTableId: !Ref "VIRBIOINFOPRODRTB"

  VIRBIOINFOPRODRTBPROPAGATIONBZ:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VBZATTACH"
      TransitGatewayRouteTableId: !Ref "VIRBIOINFOPRODRTB"

  ONPREMRTBPROPAGATION:
   Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
   Properties:
     TransitGatewayAttachmentId: !Ref "VIRBIOINFOPRODATTACH"
     TransitGatewayRouteTableId: !Ref "ONPREMRTB"

#  INFRASTRUCTURERTBPROPAGATION:
#   Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
#   Properties:
#     TransitGatewayAttachmentId: !Ref "VIRBIOINFOPRODATTACH"
#     TransitGatewayRouteTableId: !Ref "INFRASTRUCTURERTB"
