AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for creating VPC Transit Gateway Attachment'

Parameters:

  VSFATTACH:
    Description: San Francisco VPN Attachment
    Type: String
    Default: tgw-attach-0ddf2dedf06c33986

  VSF2ATTACH:
    Description: San Francisco 1800 VPN Attachment
    Type: String
    Default: tgw-attach-0f3edf91cbe8ea3f4

  VPDXATTACH:
    Description: Portland VPN Attachment
    Type: String
    Default: tgw-attach-0ee5940ee1c803d10

  VSTLATTACH:
    Description: St Louis VPN Attachment
    Type: String
    Default: tgw-attach-04cd3cd716b6c0622

  VBZATTACH:
    Description: Bellenzona VPN Attachment
    Type: String
    Default: tgw-attach-02a4c8d66379491b0

  VPCNAME:
    Description: VPC Name
    Type: String
    Default: INFRASTRUCTURE

  VPCID:
    Description: VPC ID
    Type: String
    Default: vpc-071fd2f624fc6ebad

  LOCATION:
    Description: AWS Region
    Type: String
    AllowedValues:
      - USW2
      - USE1
      - EUC1

  ONPREMRTB:
    Description: Default Route Table
    Type: String
    Default: tgw-rtb-009e797b726ddabe7


  PVTSUBNET1:
    Description: Private Subnet ID in AZ1
    Type: String
    Default: subnet-00abc1f3dffe75730

  PVTSUBNET2:
    Description: Private Subnet ID in AZ2
    Type: String
    Default: subnet-08d335a27d5ecf9a7

  TGWID:
    Description: Transit Gateway ID (USW2-TGW-0636048e0a4a4d640 / USE1-TGW-0f420529ad2f44f8b)
    Type: String
    AllowedValues:
      - tgw-0636048e0a4a4d640
      - tgw-0f420529ad2f44f8b

Resources:
  INFRAATTACH:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId: !Ref "TGWID"
      VpcId: !Ref "VPCID"
      SubnetIds:
        - !Ref "PVTSUBNET1"
        - !Ref "PVTSUBNET2"
      Tags:
        - Key: Name
          Value: !Ref "VPCNAME"

  INFRARTB:
    Type: "AWS::EC2::TransitGatewayRouteTable"
    Properties:
      TransitGatewayId: !Ref "TGWID"
      Tags:
        - Key: Name
          Value: !Ref "VPCNAME"

  INFRARTBASSOCIATION:
    Type: "AWS::EC2::TransitGatewayRouteTableAssociation"
    DependsOn: INFRARTB
    Properties:
      TransitGatewayAttachmentId: !Ref "INFRAATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  INFRARTBPROPAGATIONVSF:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VSFATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  INFRARTBPROPAGATIONVSF2:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VSF2ATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  INFRARTBPROPAGATIONPDX:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VPDXATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  INFRARTBPROPAGATIONSTL:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VSTLATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  INFRARTBPROPAGATIONBZ:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VBZATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  ONPREMRTBPROPAGATION:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    DependsOn: INFRAATTACH
    Properties:
      TransitGatewayAttachmentId: !Ref "INFRAATTACH"
      TransitGatewayRouteTableId: !Ref "ONPREMRTB"
