AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'This template creates two IAM roles 1. Administrator Access, 2. ReadOnly Access in IOVANCE LogArchive Account.'

Parameters:
  AdministratorAccess:
    Type: String
    Description: 'ARN of AWS managed policy'
    Default: 'arn:aws:iam::aws:policy/AdministratorAccess'
  ReadOnlyAccess:
    Type: String
    Description: 'ARN of AWS managed policy'
    Default: 'arn:aws:iam::aws:policy/ReadOnlyAccess'

Resources:
   SharedServicesEC2L2Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Sid: Deny Policy to restrict specific operations
            Effect: Deny
            Action:
              - ec2:DeleteKeyPair
              - ec2:DeleteNetworkInterface
              - ec2:DeleteSnapshot
              - ec2:DeleteTags
              - ec2:DeleteVolume
              - ec2:DeregisterImage
              - ec2:DetachNetworkInterface
              - ec2:TerminateInstances

            Resource: "arn:aws:ec2:*:ACCOUNT-ID:instance/*"
            -----------------------------------------------------
   AWSLogArchiveAdministratorAccess:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'AWS_LogArchive_AdministratorAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref AdministratorAccess

   AWSLogArchiveReadOnlyAccess:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'AWS_LogArchive_ReadOnlyAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref ReadOnlyAccess
