AWSTemplateFormatVersion: '2010-09-09'
Description: Vir Biotechnology. CloudFormation template that provisions single EC2 Instance.

Parameters:

  Name:
    Description:  Specify the server name
    Type:         String

  EC2InstanceType:
    Description:  Amazon EC2 instance type
    Type:         String
    Default:      t2.medium

  IMAGEID:
    Description: AMI id of the EC2 instance
    Type:        String

  SUBNETID:
    Description: Subnet ID
    Type:        String

  SECURITYGROUPID:
    Description: Security Group IDs
    Type:        String
    Default:     "On-Prem_Plus_VPC"


  VPCName:
    Description:  Specify the VPC Name
    Type:         String
    AllowedValues:
      - INFRASTRUCTURE

  KeyPairName:
    Description: Public/private key pairs allow you to securely connect to your instance after it launches
    Type: 'AWS::EC2::KeyPair::KeyName'

  BootVolSize:
    Description:    EC2 Boot volume size
    Type:           String
    Default:        "16"

  BootVolType:
    Description:    EC2 Boot volume type
    Type:           String
    Default:        "gp2"
    AllowedValues:
      - gp2
      - io1
      - sc1
      - st1

  DelOnTerm:
    Description:    EBS termination
    Type:           String
    Default:        "false"
    AllowedValues:
      - true
      - false



Resources:

# EC2 Instance
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref "IMAGEID"
      AvailabilityZone: !Select ['0', !GetAZs {Ref: 'AWS::Region'}]
      InstanceType: !Ref 'EC2InstanceType'
      SubnetId: !Ref "SUBNETID"
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref "BootVolSize"
            VolumeType: !Ref "BootVolType"
            DeleteOnTermination: !Ref "DelOnTerm"

      KeyName: !Ref 'KeyPairName'
      Tags:
        - Key: "Application"
          Value: "value1"
        - Key: "Owner"
          Value: "Vir Bio"
        - Key: "AppName"
          Value: "N/A"
        - Key: "Backup"
          Value: "Enabled"
        - Key: "BusinessUnit"
          Value: "N/A"
        - Key: "Classification"
          Value: "N/A"
        - Key: "Date-Created"
          Value: "20JAN2020"
        - Key: "Environment"
          Value: "Prod"
        - Key: "Managed-By"
          Value: "CloudFormation"
        - Key: "Monitoring"
          Value: "N/A"
        - Key: "Name"
          Value: "cdr-prod"
        - Key: "Notes"
          Value: "value2"
        - Key: "Retention-days"
          Value: "value1"
        - Key: "ssm"
          Value: "value2"
        - Key: "SysOwner"
          Value: "value1"
        - Key: "Auto-Shutdown"
          Value: "value2"


Outputs:

  EC2InstanceIP:
    Description: EC2 IP Address
    Value: !GetAtt 'EC2Instance.PrivateIp'

  EC2InstanceID:
    Description: EC2 Instance ID
    Value: !Ref 'EC2Instance'
