AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for creating VPC Transit Gateway Attachment'

Parameters:

  VSFATTACH:
    Description: San Francisco VPN Attachment
    Type: String
    Default: tgw-attach-08f9ea1b799ea2732

  VSF2ATTACH:
    Description: San Francisco 1800 VPN Attachment
    Type: String
    Default: tgw-attach-0728e03ecd8f9d841

  VPDXATTACH:
    Description: Portland VPN Attachment
    Type: String
    Default: tgw-attach-0b3f92f7bb9f6c86e

  VSTLATTACH:
    Description: St Louis VPN Attachment
    Type: String
    Default: tgw-attach-0caeb220bbbc103e6

  VBZATTACH:
    Description: Bellenzona VPN Attachment
    Type: String
    Default: tgw-attach-04fba10c06188714f

  VPCNAME:
    Description: VPC Name
    Type: String

  VPCID:
    Description: VPC ID
    Type: String

  LOCATION:
    Description: AWS Region
    Type: String
    AllowedValues:
      - USW2
      - USE1
      - EUC1

  ONPREMRTB:
      Description: Default Route Table
      Type: String
      Default: tgw-rtb-06fb1a0a41edb79a2



  PVTSUBNET1:
    Description: Private Subnet ID in AZ1
    Type: String

  PVTSUBNET2:
    Description: Private Subnet ID in AZ2
    Type: String

  TGWID:
    Description: Transit Gateway ID
    Type: String
    AllowedValues:
      - tgw-0636048e0a4a4d640
      - tgw-0f420529ad2f44f8b

Resources:
  INFRAATTACH:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId: !Ref "TGWID"
      VpcId: !Ref "VPCID"
      SubnetIds:
        - !Ref "PVTSUBNET1"
        - !Ref "PVTSUBNET2"
      Tags:
        - Key: Name
          Value: !Ref "VPCNAME"

  INFRARTB:
    Type: "AWS::EC2::TransitGatewayRouteTable"
    Properties:
      TransitGatewayId: !Ref "TGWID"
      Tags:
        - Key: Name
          Value: !Ref "VPCNAME"

  INFRARTBASSOCIATION:
    Type: "AWS::EC2::TransitGatewayRouteTableAssociation"
    DependsOn: INFRARTB
    Properties:
      TransitGatewayAttachmentId: !Ref "INFRAATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  INFRARTBPROPAGATIONVSF:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VSFATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  INFRARTBPROPAGATIONVSF2:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VSF2ATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  INFRARTBPROPAGATIONPDX:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VPDXATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  INFRARTBPROPAGATIONSTL:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VSTLATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  INFRARTBPROPAGATIONBZ:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    Properties:
      TransitGatewayAttachmentId: !Ref "VBZATTACH"
      TransitGatewayRouteTableId: !Ref "INFRARTB"

  ONPREMRTBPROPAGATION:
    Type: "AWS::EC2::TransitGatewayRouteTablePropagation"
    DependsOn: INFRAATTACH
    Properties:
      TransitGatewayAttachmentId: !Ref "INFRAATTACH"
      TransitGatewayRouteTableId: !Ref "ONPREMRTB"
